[[pages]]
path = "main.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/visualization.py"
name = "2D Visualization"
icon = "📊"

[[pages]]
path = "pages/classification.py"
name = "Classification ML Algorithms"
icon = "🎯"

[[pages]]
path = "pages/clustering.py"
name = "Clustering ML Algorithms"
icon = "🧩"

[[pages]]
path = "pages/info.py"
name = "Information"
icon = "ℹ️"